#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 I II III IV V
bspc monitor DP-3  VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config click_to_focus button1

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Lightcord state=floating
bspc rule -a Shutter state=floating

# custom color sources
# Special
background='#0a090a'
foreground='#dee1e3'
cursor='#dee1e3'

# Colors
color0='#84B8CD'
color1='#3CE5D8'
color2='#A39DA7'
color3='#DFA7AA'
color4='#84B8CD'

bspc config focused_border_color \#3CE5D8

feh --bg-fill Images/Wallpaper/dragon-blue.pnp

picom
conky.sh
